results_dir: "./exp/"
vis_test_dir: "/nas/home/jihyokim/jm/CRAFT-Refactoring-v2/exp/viz"
wandb_opt: False

data_dir:
  synthtext: "/data/SynthText/"
  synthtext_gt: NULL
  synthtext_kor : "/nas/datahub/SynthText-KR"
  ai_hub : "/nas/datahub/ai-hub-data/textinthewild_data/all_image"
  ai_hub_gt : "/nas/datahub/ai-hub-data/textinthewild_data/last_new_a100.json"
  prescription: "/nas/datahub/prescription/"

train:
  backbone : resnet
  dataset: ["synthtext_kor"]
  ckpt_path: null
  batch_size: 6
  st_iter: 0
  end_iter: 60000
  lr: 0.0001
  lr_decay: 15000
  gamma: 0.2
  weight_decay: 0.00001
  num_workers: 4
  amp: True
  loss: 3
  neg_rto: 1
  n_min_neg: 1000



test:
  #trained_model: "/nas/home/jihyokim/jm/pre-trained-model/craft_general.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/shwang_synthtext_test6_26-1/CRAFT_clr_amp_60000.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/syn_baseline_eng_kor/CRAFT_clr_amp_60000.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/syn_baseline_eng_kor_v2/CRAFT_clr_amp_60000.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/syn_baseline_eng_kor_ai_hub/CRAFT_clr_amp_60000.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/syn_resnet_ori_v2_result/syn_resnet_ori_v2/CRAFT_clr_amp_60000.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/syn_resnet_ori_v2_result/syn_resnet_ori_v2_en_ko/CRAFT_clr_amp_60000.pth"
  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring/exp/syn_resnet_ori_v2_result/syn_resnet_eng_kor_ai_hub_test/CRAFT_clr_amp_60000.pth"


  #trained_model: "/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip_train_v2/CRAFT_clr_amp_6500.pth"
  #trained_model: '/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip-resnet-long/CRAFT_clr_amp_50000.pth'
  #trained_model: '/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip_resnet_neg1_en_y0.25/CRAFT_clr_amp_last50000.pth'
  #trained_model: '/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip_v2_resnet_neg1_en0.3/CRAFT_clr_amp_last50000.pth'
  #trained_model: '/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip_v3_resnet_neg1_en0.3/CRAFT_clr_amp_last80000.pth'
  #trained_model: '/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip_v3_resnet_neg1_en0.3-multiscale/CRAFT_clr_amp_last80000.pth'
  trained_model: '/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/prescrip_v3_resnet_neg1_en0.3-multiscale-v2/CRAFT_clr_amp_last80000.pth'
  icdar2013:
    cuda: True
    vis_opt: True
    test_data_dir : "/nas/datahub/ICDAR2013/"
    text_threshold: 0.85 # ICDAR2015 0.85
    low_text: 0.5 # ICDAR2015 0.5
    link_threshold: 0.2 # ICDAR2013: 0.2
    canvas_size: 960
    mag_ratio: 1.5
    poly: False
  icdar2015:
    cuda: True
    vis_opt: True
    test_data_dir: "/nas/datahub/ICDAR2015/"
    text_threshold: 0.85 # ICDAR2015 0.85
    low_text: 0.5 # ICDAR2015 0.5
    link_threshold: 0.2 # ICDAR2013: 0.2
    canvas_size: 2240
    mag_ratio: 1.75
    poly: False
  prescription:
    cuda: True
    vis_opt: True
    test_data_dir: "/nas/datahub/prescription/"
    text_threshold: 0.687 # ICDAR2015 0.85
    low_text: 0.4 # ICDAR2015 0.5
    link_threshold: 0.205 # ICDAR2013: 0.2
    canvas_size: 2560
    mag_ratio: 1.
    poly: False

#  prescription:
#    cuda: True
#    vis_opt: True
#    test_data_dir: "/nas/datahub/prescription/"
#    text_threshold: 0.687 # ICDAR2015 0.85
#    low_text: 0.4 # ICDAR2015 0.5
#    link_threshold: 0.205 # ICDAR2013: 0.2
#    canvas_size: 2560
#    mag_ratio: 1.
#    poly: False