results_dir: "./exp/"
vis_test_dir: "/nas/home/jihyokim/jm/CRAFT-Refactoring-0324/exp/viz/test"
#vis_test_dir: "/nas/home/gmuffiness/result/debug_ic15_weak_supervision"
wandb_opt: False

data_dir:
  synthtext: "/data/SynthText/"
  synthtext_gt: NULL
  synthtext_kor : "/data/SynthText-KR"
  prescrip_train : "/data/prescription-train/"
  ic15: "/data/ICDAR2015/"
  ic15_gt: NULL

train:
  backbone: resnet
  syn_dataset : ["synthtext", "synthtext_kor"]
  real_dataset: prescription
  ckpt_path: "/nas/home/shwang/workspace/CRAFT-Refactoring/exp/syn_en_ko_resnet/CRAFT_clr_amp_60000.pth"
  #ckpt_path: "/nas/home/jihyokim/jm/CRAFT-Refactoring/config/shwang_test26_CRAFT_clr_amp_60000.pth"
  eval_interval: 1000
  batch_size: 10
  st_iter: 0
  end_iter: 50000 #
  lr: 0.0001
  lr_decay: 20000
  gamma: 0.2
  weight_decay: 0.00001
  num_workers: 4
  amp: True
  loss: 2
  neg_rto: 0.3
  n_min_neg: 5000
  data:
    vis_opt: False
    pseudo_vis_opt: False
    output_size: 768
    do_not_care_label: ['###', '']
    mean: [0.485, 0.456, 0.406]
    variance: [0.229, 0.224, 0.225]
    enlarge_region : [0.5, 0.5] # x axis, y axis
    enlarge_affinity: [0.5, 0.5]
    gauss_init_size: 200
    gauss_sigma: 40
    watershed:
      version: "skimage"
      sure_fg_th: 0.75
      sure_bg_th: 0.05
    syn_sample: 150000
    prescrip_sample: -1
    syn_aug:
      random_scale:
        range: [1.0, 1.5, 2.0]
        option: False
      random_rotate:
        max_angle: 20
        option: False
      random_crop:
        version: "random_resize_crop_synth"
        scale: [0.333, 1.0]
        ratio: [0.75, 1.333]
        option: True
      random_horizontal_flip:
        option: False
      random_colorjitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
        option: True
    syn_kor_aug:
      random_scale:
        range: [ 1.0, 1.5, 2.0 ]
        option: False
      random_rotate:
        max_angle: 20
        option: False
      random_crop:
        version: "random_resize_crop_synth"
        scale: [ 0.333, 1.0 ]
        ratio: [ 0.75, 1.333 ]
        option: True
      random_horizontal_flip:
        option: False
      random_colorjitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
        option: True
    prescrip_aug:
      random_scale:
        range: [ 1.0, 1.5, 2.0 ]
        option: False
      random_rotate:
        max_angle: 20
        option: True
      random_crop:
        version: "random_resize_crop"
        scale: [ 0.05, 0.2 ]
        ratio: [ 0.75, 1.33 ]
        rnd_threshold: 1
        option: True
      random_horizontal_flip:
        option: True
      random_colorjitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
        option: True

test:
  trained_model : null
  icdar2013:
    test_set_size: 233
    test_data_dir : "/data/ICDAR2013/"
    text_threshold: 0.85 # ICDAR2015 0.85
    low_text: 0.5 # ICDAR2015 0.5
    link_threshold: 0.2 # ICDAR2013: 0.2
    canvas_size: 960
    mag_ratio: 1.5
    poly: False
    cuda: True
    vis_opt: True
  icdar2015:
    test_set_size: 500
    cuda: True
    vis_opt: True
    test_data_dir: "/data/ICDAR2015/"
    text_threshold: 0.85 # ICDAR2015 0.85
    low_text: 0.5 # ICDAR2015 0.5
    link_threshold: 0.2 # ICDAR2013: 0.2
    canvas_size: 2240
    mag_ratio: 1.75
    poly: False
  prescription:
    test_set_size: 87
    test_data_dir: "/data/prescription/"
    text_threshold: 0.1 # ICDAR2015 0.85
    low_text: 0.25 # ICDAR2015 0.5
    link_threshold: 0.4 # ICDAR2013: 0.2
    canvas_size: 2560
    mag_ratio: 1.
    poly: False
    cuda: True
    vis_opt: True
