results_dir: "./exp/"
vis_test_dir: "/nas/home/jihyokim/jm/CRAFT-Refactoring-v2/exp/viz"
wandb_opt: False

data_dir:
  synthtext: "/data/SynthText/"
  synthtext_gt: NULL
  synthtext_kor : "/nas/datahub/SynthText-KR"
  ai_hub : "/nas/datahub/ai-hub-data/textinthewild_data/all_image"
  ai_hub_gt : "/nas/datahub/ai-hub-data/textinthewild_data/last_new_a100.json"
  prescription: "/nas/datahub/prescription/"

train:
  ckpt_path: null
  batch_size: 48
  st_iter: 0
  end_iter: 60000
  lr: 0.0001
  lr_decay: 15000
  gamma: 0.2
  weight_decay: 0.00001
  num_workers: 4
  amp: True
  loss: 3
  neg_rto: 1
  n_min_neg: 1000
  data:
    vis_opt: False
    output_size: 768
    enlarge_region : [0.5, 0.5] # x axis, y axis
    enlarge_affinity: [0.5, 0.5]
    gauss_init_size: 200
    gauss_sigma: 40
    syn_sample : 150000
    syn_aug:
      random_scale:
        range: [1.0, 1.5, 2.0]
        option: False
      random_rotate:
        max_angle: 20
        option: False
      random_crop:
        version: "random_resize_crop"
        scale: [0.2, 0.8]
        ratio: [0.75, 1.333]
        option: True
      random_horizontal_flip:
        option: False
      random_colorjitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.2
        option: True


test:
  vis_opt: False
  test_data_dir: "/data/ICDAR2015/"
  trained_model: null
  text_threshold: 0.85 # ICDAR2015 0.85
  low_text: 0.5 # ICDAR2015 0.5
  link_threshold: 0.2 # ICDAR2013: 0.2
  cuda: True
  canvas_size:
    icdar2013: 960
    icdar2015: 2240
  mag_ratio: 1.75
  poly: False
